configType: "linux" # "windows" or "linux"

windows:
  dotfiles:
    path: "Documents/Code/dotfiles"
  obsidian:
    vaultpath: "Documents/Obsidian Vault"

linux:
  dotfiles:
    path: ".dotfiles"
  obsidian:
    vaultpath: "/mnt/c/Users/matko/Documents/Obsidian Vault"
