inherits = "gruvbox"

"constructor" = { fg = "purple1" }
"function" = { fg = "green1" }
"constant.builtin" = { fg = "purple1" }
"constant.character.escape" = { fg = "fg2" }
"ui.menu.selected" = { fg = "bg2", bg = "blue1" }
"ui.text.focus" = { fg = "fg1", modifier = ["bold"] }
