device: desktop
paths:
  obsidianvault: C:\Users\matko\documents\Obsidian Vault
  website: C:\Users\matko\documents\Code\matkv.dev
  dotfiles:
    repo: C:\Users\matko\Documents\Code\dotfiles
    apps:
      neovim:
        sources:
          - .config\nvim\init.lua
        target: C:\Users\matko\AppData\Local\nvim
      core:
        sources:
          - .config\core\config.yaml
        target: C:\Users\matko\AppData\Roaming\core
