device: desktop
paths:
  obsidianvault: C:\Users\matko\documents\Obsidian Vault
  website: C:\Users\matko\documents\Code\matkv.dev
  dotfiles:
    repo: C:\Users\matko\Documents\Code\dotfiles
    apps:
      neovim:
        sources:
          - .config\nvim\init.lua
        target: C:\Users\matko\AppData\Local\nvim
      core:
        sources:
          - .config\core\config.yaml
        target: C:\Users\matko\AppData\Roaming\core
      vscode:
        sources:
          - .config\Code\User\settings.json
          - .config\Code\User\keybindings.json
        target: C:\Users\matko\AppData\Roaming\Code\User
      wezterm:
        sources:
          - .wezterm.lua
        target: C:\Users\matko\
      powershell:
        sources:
          - .powershell\Microsoft.PowerShell_profile.ps1
        target: C:\Users\matko\Documents\PowerShell\
