# to-do: go through all options at https://docs.helix-editor.com/configuration.html 
# and add them here and decide what settings to set

theme = "gruvbox"

[editor]
line-number = "absolute"
middle-click-paste = true  # doesn't seem to work with kitty (Ctrl+Shift+V works though)
cursorline = true
color-modes = true
rulers = []                # decide if necessary

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true