theme = "everforest_dark"

[editor]
line-number = "absolute"
middle-click-paste = true  
cursorline = true
color-modes = true
rulers = []                # decide if necessary
bufferline = "always"
completion-trigger-len = 1
idle-timeout = 200
auto-info = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-signature-help-docs = true
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "┊"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "file-type", "position-percentage", "position", "file-encoding"]

# enable cursor movement with arrow keys in insert mode
[keys.insert]
up = "move_line_up"
down = "move_line_down"
left = "move_char_left"
right = "move_char_right"